apiVersion: v1
kind: Template
labels:
  template: naming-service-deployment
  thoth: 0.1.0
metadata:
  name: naming-service-deployment
  annotations:
    description: This is Thoth Naming Service DeploymentConfig, this template is meant to be used by Jenkins, but could also be used by humans...
    openshift.io/display-name: "Thoth Core: Naming Service"
    version: 0.1.0
    tags: poc,thoth,naming-service,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This is Thoth Naming Service DeploymentConfig, this template is meant to be used by Jenkins, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- kind: Route
  apiVersion: v1
  metadata:
    name: naming-service
    labels:
      app: thoth-core
      component: naming-service
  spec:
    to:
      kind: Service
      name: naming-service

- kind: Service
  apiVersion: v1
  metadata:
    labels:
      service: naming-service
      app: thoth-core
      component: naming-service
    name: naming-service
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      service: naming-service

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      service: naming-service
      app: thoth-core
      component: naming-service
    name: naming-service
  spec:
    replicas: 1
    selector:
      service: naming-service
    template:
      metadata:
        labels:
          service: naming-service
      spec:
        containers:
        - name: naming-service
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: '/readiness'
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: '/liveness'
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 10
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - naming-service
        from:
          kind: ImageStreamTag
          name: 'naming-service:latest'
